repos:
  - repo: local
    hooks:
      - id: unit-tests
        name: unit-tests
        entry: poetry run coverage run
        args: [
          '-m',
          'pytest',
          '-capture=no'
        ]
        pass_filenames: false
        language: system
        types: [python]
      - id: bandit
        name: bandit
        entry: poetry run bandit
        files: headache/
        language: system
        types: [python]
      - id: isort
        name: isort
        description: isort sorts your imports
        entry: poetry run isort
        args: [
          '--check-only'
        ]
        require_serial: true
        language: python
        language_version: python3
        types_or: [cython, pyi, python]
        minimum_pre_commit_version: '2.9.0'
      - id: black
        name: black
        entry: poetry run black
        args: [
          '--check'
        ]
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: poetry run flake8
        args: [
          '--config',
          '.flake8'
        ]
        files: headache/
        language: system
        types: [python]
      - id: mypy
        name: mypy
        entry: poetry run mypy
        args: [
          '--config-file',
          '.mypy.ini',
          '--show-error-codes'
        ]
        files: headache/
        language: system
        types: [python]
      - id: safety
        name: safety
        entry: poetry run safety
        args: [
          'check',
          '--full-report'
        ]
        pass_filenames: false
        language: system
        types: [python]
